INSERT INTO
  books (
    id,
    slug,
    title,
    subtitle,
    description,
    longDescription,
    cover_image,
    publish_date,
    status,
    author,
    world_slug,
    series_slug,
    characterSlugs,
    formats,
    excerpt,
    related,
    badges,
    tags,
    ogImage,
    published
  )
VALUES
  -- Book 1
  (
    1,
    'true-story-of-trafalgar',
    'The True Story of Trafalgar',
    'Volume One',
    'A famous square. A legendary battle. The untold lives behind the history.',
    'Today we can travel to London and experience the many historical sites, including beautiful Trafalgar Square, in the area known as Charing Cross. We think that the statue of Admiral Nelson that stands watch on top of the tall column represents the Battle of Trafalgar and the naming of the square, but it is only a small part of a greater story that involves the lives of many people. The True Story of Trafalgar reveals the names and details of many persons recorded in history and many others who lived their lives in relative anonymity, but perhaps enjoying life every bit as much as their famous counterparts. Welcome to volume one taking place primarily in London and Garristown, Ireland, where George and Riley show us that life and love can be very complicated.',
    '/images/books/trafalgar/trafalgar1.png',
    '2025-07-25',
    'available',
    'C.R. Thompson',
    'trafalgar',
    'trafalgar',
    '["george","riley"]',
    '[{"type":"kindle","label":"Kindle","url":"https://www.amazon.com/True-Story-Trafalgar-One-ebook/dp/B0FK1XDKD5"},{"type":"audiobook","label":"Audiobook","url":"https://www.amazon.com/True-Story-Trafalgar-One/dp/B0FMKHFDB6"}]',
    'TBD',
    '{"prequelSlug":null,"nextSlug":null,"previousSlug":null}',
    '["Historical Fiction"]',
    '["historical fiction","london","ireland","trafalgar","character-driven"]',
    '/images/og/books/true-story-of-trafalgar.jpg',
    1
  ),
  -- Book 2
  (
    2,
    'power-seven',
    'Power Seven',
    NULL,
    'When catastrophe strikes, the truth hides in plain sight.',
    'Strange phenomena are observed during chaotic and catastrophic events around the world. Efforts to discover the cause are finding nothing. David Stone is assigned to investigate one of the scenes, where he found violent actions seen only on the worst battlefields. Politics seem to be thwarting his best efforts to solve the mystery. The truth is hard to find and harder to accept. Hoping to stop a worldwide catastrophe, Stone needs help and it seems to come from the most unlikely sources.',
    '/images/books/powerseven/powerseven1.png',
    '2024-06-12',
    'available',
    'C.R. Thompson',
    'power-seven',
    'power-seven',
    '["david-stone"]',
    '[{"type":"kindle","label":"Kindle","url":"https://www.amazon.com/Power-Seven-C-R-Thompson-ebook/dp/B0D6YZWRJP"},{"type":"audiobook","label":"Audiobook","url":"https://www.amazon.com/Audible-Power-Seven/dp/B0CZ4N4LZV"},{"type":"paperback","label":"Paperback","url":"https://www.amazon.com/Power-Seven-C-R-Thompson/dp/B0D7QNX41K"}]',
    'TBD',
    '{"prequelSlug":null,"nextSlug":null,"previousSlug":null}',
    '["Sci-Fi Thriller"]',
    '["science fiction","thriller","mystery","global catastrophe","conspiracy"]',
    '/images/og/books/power-seven.jpg',
    1
  ),
  -- Book 3
  (
    3,
    'alex',
    'Alex',
    'Tales of the Labyrinth Nebula · Book 1',
    'A single encounter can change the course of a life—and a universe.',
    'As young boys, growing up on Earth, Alex and his brother Ryan have a brief encounter with the strange alien, C621. From that moment on, Alex knows that his destiny is in the stars. The path is not always clear or easy, but it is definitely life changing. Alex was originally published on Kindle Vella as one of the Top Faved Science Fiction stories. Alex is the prequel to the even larger story that continues with Alex’s daughter, Dorian in the Tales of the Labyrinth Nebula series by C. R. Thompson, published on Amazon, for Kindle eBooks and in paperback. Dorian: Volume 3 is coming soon (previously on Vella).',
    '/images/books/tln/alex1.png',
    '2022-11-28',
    'available',
    'C.R. Thompson',
    'tales-of-the-labyrinth-nebula',
    'tln',
    '["alex-fox","c621"]',
    '[{"type":"kindle","label":"Kindle","url":"https://www.amazon.com/gp/product/B0BNLSLCMH"},{"type":"audiobook","label":"Audiobook","url":"https://www.amazon.com/Audible-Alex/dp/B0CY4YLQW9"},{"type":"paperback","label":"Paperback","url":"https://www.amazon.com/Alex-Tales-Labyrinth-Nebula-Thompson/dp/B0BMZ85NBF"}]',
    'TBD',
    '{"prequelSlug":null,"nextSlug":"dorian-volume-1","previousSlug":null}',
    '["Space Opera","Kindle Vella"]',
    '["science fiction","space opera","first contact","origin story","tln"]',
    '/images/og/books/alex.jpg',
    1
  ),
  -- Book 4
  (
    4,
    'dorian-volume-1',
    'Dorian – Volume 1',
    'Tales of the Labyrinth Nebula · Book 2',
    'The universe is calling—and the answers lie beyond Earth.',
    'What is the Earth Window? Who is Ck5? Where are the voices coming from? Driven by memories of her famous Astronaut father, Alex Fox, Dorian is on her way to the new Polaris Lunar Mining Base. It is only the beginning of her journey and nothing seems to happen as planned. The Defense Alliance needs her help and she needs answers. With only fragments of family stories, Dorian hopes that going to the stars will help her to discover the parents that she never really knew. In many ways Dorian is exceptional, but she is also filled with doubts about meeting the challenges of the future. During her Polaris training she met Adam Casey, a self-assured and exceptional pilot astronaut. Adam helps Dorian with her confidence and skills. He is her rock and the close relationship that Dorian never expected. Together they make amazing discoveries that change the direction of both of their lives forever. Dorian, Volume 1 is just the first in the Dorian series telling her fantastic story. We are not alone in this Universe and we have a lot to learn.',
    '/images/books/tln/dorian1.png',
    '2019-11-04',
    'available',
    'C.R. Thompson',
    'tales-of-the-labyrinth-nebula',
    'tln',
    '["dorian-fox","adam-casey"]',
    '[{"type":"kindle","label":"Kindle","url":"https://www.amazon.com/Dorian-Tales-Labyrinth-Nebula-Dorians-ebook/dp/B0811FHP1L"},{"type":"audiobook","label":"Audiobook","url":"https://www.amazon.com/Dorian-Volume-1-Extended-Edition/dp/B0DT91GL9D"},{"type":"paperback","label":"Paperback","url":"https://www.amazon.com/Dorian-Tales-Labyrinth-Nebula-Dorians/dp/1705662412"}]',
    'TBD',
    '{"prequelSlug":"alex","nextSlug":"dorian-volume-2","previousSlug":null}',
    '["Space Opera"]',
    '["science fiction","space opera","lunar base","mystery","earth window","tln"]',
    '/images/og/books/dorian-volume-1.jpg',
    1
  ),
  -- Book 5
  (
    5,
    'dorian-volume-2',
    'Dorian – Volume 2',
    'Tales of the Labyrinth Nebula · Book 3',
    'Distance changes everything—but destiny remains.',
    'On the far side of the Earth Window Dorian Fox is standing watch as an officer for the Defense Alliance. Her friend and love, Adam Casey is on the Earth side of the window, working on the development of new Defense Alliance ships needed for their defense against the ever present, Tech threat. Dorian: Vol 2 begins after Dorian and Casey have been apart for several Earth years. It is clear that their lives are being pulled in different directions. The Labyrinth Nebula holds many secrets, and it seems to be Dorian’s destiny to unravel the mysteries.',
    '/images/books/tln/dorian2.png',
    '2021-05-03',
    'available',
    'C.R. Thompson',
    'tales-of-the-labyrinth-nebula',
    'tln',
    '["dorian-fox","adam-casey"]',
    '[{"type":"kindle","label":"Kindle","url":"https://www.amazon.com/gp/product/B0942PHDX3"},{"type":"paperback","label":"Paperback","url":"https://www.amazon.com/Dorian-2-C-R-Thompson/dp/B094281ZQ3"}]',
    'TBD',
    '{"prequelSlug":"alex","nextSlug":"dorian-volume-3","previousSlug":"dorian-volume-1"}',
    '["Space Opera"]',
    '["science fiction","space opera","earth window","defense alliance","tln"]',
    '/images/og/books/dorian-volume-2.jpg',
    1
  ),
  -- Book 6
  (
    6,
    'dorian-volume-3',
    'Dorian – Volume 3',
    'Tales of the Labyrinth Nebula · Book 4',
    'Coming soon: the next chapter in the Labyrinth Nebula saga.',
    'TBD',
    '/images/books/tln/dorian3.png',
    'TBD',
    'coming_soon',
    'C.R. Thompson',
    'tales-of-the-labyrinth-nebula',
    'tln',
    '["dorian-fox","adam-casey"]',
    '[]',
    NULL,
    '{"prequelSlug":"alex","nextSlug":null,"previousSlug":"dorian-volume-2"}',
    '["Coming Soon"]',
    '["science fiction","space opera","tln"]',
    '/images/og/books/dorian-volume-3.jpg',
    0
  ) ON CONFLICT (slug) DO
UPDATE
SET
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  longDescription = excluded.longDescription,
  cover_image = excluded.cover_image,
  publish_date = excluded.publish_date,
  status = excluded.status,
  author = excluded.author,
  world_slug = excluded.world_slug,
  series_slug = excluded.series_slug,
  characterSlugs = excluded.characterSlugs,
  formats = excluded.formats,
  excerpt = excluded.excerpt,
  related = excluded.related,
  badges = excluded.badges,
  tags = excluded.tags,
  ogImage = excluded.ogImage,
  published = excluded.published;